package goentdb

type Origin uint

const (
	OriginUnkown     Origin = 0
	OriginXvideos    Origin = 1
	OriginPorntube   Origin = 2
	OriginEporner    Origin = 3
	OriginPornone    Origin = 4
	OriginCumlouder  Origin = 5
	OriginSuperporn  Origin = 6
	OriginAlphaporno Origin = 8
)

var OriginNames = []string{
	"Unkown",
	"Xvideos",
	"Porntube",
	"Eporner",
	"Pornone",
	"Cumlouder",
	"Superporn",
	"Alphaporno",
}

type EntKeywordType uint

const (
	EntKeywordTag EntKeywordType = iota
	EntKeywordModel
	EntKeywordKeyword
)

var StopWords = []string{
	"i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you",
	"you're", "you've", "you'll", "you'd", "your", "yours", "yourself",
	"yourselves", "he", "him", "his", "himself", "she", "she's", "her",
	"hers", "herself", "it", "it's", "its", "itself", "they", "them",
	"their", "theirs", "themselves", "what", "which", "who", "whom",
	"this", "that", "that'll", "these", "those", "am", "is", "are",
	"was", "were", "be", "been", "being", "have", "has", "had", "having",
	"do", "does", "did", "doing", "a", "an", "the", "and", "but", "if",
	"or", "because", "as", "until", "while", "of", "at", "by", "for",
	"with", "about", "against", "between", "into", "through", "during",
	"before", "after", "above", "below", "to", "from", "up", "down",
	"in", "out", "on", "off", "over", "under", "again", "further", "then",
	"once", "here", "there", "when", "where", "why", "how", "all", "any",
	"both", "each", "few", "more", "most", "other", "some", "such", "no",
	"nor", "not", "only", "own", "same", "so", "than", "too", "very", "s",
	"t", "can", "will", "just", "don", "don't", "should", "should've",
	"now", "d", "ll", "m", "o", "re", "ve", "y", "ain", "aren", "aren't",
	"couldn", "couldn't", "didn", "didn't", "doesn", "doesn't", "hadn", "hadn't",
	"hasn", "hasn't", "haven", "haven't", "isn", "isn't", "ma", "mightn", "mightn't",
	"mustn", "mustn't", "needn", "needn't", "shan", "shan't", "shouldn", "shouldn't",
	"wasn", "wasn't", "weren", "weren't", "won", "won't", "wouldn", "wouldn't",
}

const TrimSymbols = ".!,:-)(/@$%^:&?*]["

var StopWordsMap = map[string]bool{
	"and":        true,
	"to":         true,
	"in":         true,
	"a":          true,
	"with":       true,
	"get":        true,
	"s":          true,
	"be":         true,
	"it":         true,
	"on":         true,
	"they":       true,
	"but":        true,
	"by":         true,
	"gg":         true,
	"go":         true,
	"he":         true,
	"hi":         true,
	"not":        true,
	"of":         true,
	"than":       true,
	"the":        true,
	"their":      true,
	"what":       true,
	"i":          true,
	"me":         true,
	"my":         true,
	"myself":     true,
	"we":         true,
	"our":        true,
	"ours":       true,
	"ourselves":  true,
	"you":        true,
	"you're":     true,
	"you've":     true,
	"you'll":     true,
	"you'd":      true,
	"your":       true,
	"yours":      true,
	"yourself":   true,
	"yourselves": true,
	"him":        true,
	"his":        true,
	"himself":    true,
	"she":        true,
	"she's":      true,
	"her":        true,
	"hers":       true,
	"herself":    true,
	"it's":       true,
	"its":        true,
	"itself":     true,
	"them":       true,
	"theirs":     true,
	"themselves": true,
	"which":      true,
	"who":        true,
	"whom":       true,
	"this":       true,
	"that":       true,
	"that'll":    true,
	"these":      true,
	"those":      true,
	"am":         true,
	"is":         true,
	"are":        true,
	"was":        true,
	"were":       true,
	"been":       true,
	"being":      true,
	"have":       true,
	"has":        true,
	"had":        true,
	"having":     true,
	"do":         true,
	"does":       true,
	"did":        true,
	"doing":      true,
	"an":         true,
	"if":         true,
	"or":         true,
	"because":    true,
	"as":         true,
	"until":      true,
	"while":      true,
	"at":         true,
	"for":        true,
	"about":      true,
	"against":    true,
	"between":    true,
	"into":       true,
	"through":    true,
	"during":     true,
	"before":     true,
	"after":      true,
	"above":      true,
	"below":      true,
	"from":       true,
	"up":         true,
	"down":       true,
	"out":        true,
	"off":        true,
	"over":       true,
	"under":      true,
	"again":      true,
	"further":    true,
	"then":       true,
	"once":       true,
	"here":       true,
	"there":      true,
	"when":       true,
	"where":      true,
	"why":        true,
	"how":        true,
	"all":        true,
	"any":        true,
	"both":       true,
	"each":       true,
	"few":        true,
	"more":       true,
	"most":       true,
	"other":      true,
	"some":       true,
	"such":       true,
	"no":         true,
	"nor":        true,
	"only":       true,
	"own":        true,
	"same":       true,
	"so":         true,
	"too":        true,
	"very":       true,
	"t":          true,
	"can":        true,
	"will":       true,
	"just":       true,
	"don":        true,
	"don't":      true,
	"should":     true,
	"should've":  true,
	"now":        true,
	"d":          true,
	"ll":         true,
	"m":          true,
	"o":          true,
	"re":         true,
	"ve":         true,
	"y":          true,
	"ain":        true,
	"aren":       true,
	"aren't":     true,
	"couldn":     true,
	"couldn't":   true,
	"didn":       true,
	"didn't":     true,
	"doesn":      true,
	"doesn't":    true,
	"hadn":       true,
	"hadn't":     true,
	"hasn":       true,
	"hasn't":     true,
	"haven":      true,
	"haven't":    true,
	"isn":        true,
	"isn't":      true,
	"ma":         true,
	"mightn":     true,
	"mightn't":   true,
	"mustn":      true,
	"mustn't":    true,
	"needn":      true,
	"needn't":    true,
	"shan":       true,
	"shan't":     true,
	"shouldn":    true,
	"shouldn't":  true,
	"wasn":       true,
	"wasn't":     true,
	"weren":      true,
	"weren't":    true,
	"won":        true,
	"won't":      true,
	"wouldn":     true,
	"wouldn't":   true,
}
